### ISSUE TITLE
How to use extract?

### ISSUE THREAD

**Issue by feloxx** [franklauterwald/KafkaOffsetFinder#2]
hi~

I'm a young fish..
I want to know how to use the extract?
I'm sorry I didn't understand the examples.

I don't understand what that means.
`s => {
  0L
}`

**Comment by JonasGroeger** [comment]
Hello Mr. Chen,

the expression (表式) `s => { 0L }` means: A function with one argument that returns a constant (常數 ): `0L`, `L` meaning `Long`.

If you have a Kafka topic with Strings (字串) as messages, and you want to find the offset where a certain message type starts, you can use this. This project will currently only find the first matching instance using binary search, so if your topic has non-ascending numbers this might not be what you want.

**Comment by feloxx** [comment]
If I just want to use the timestamp.
How should ‘extract’ write ?

For example, to get the data after a timestamp, just use the timestamp.

**Comment by JonasGroeger** [comment]
Depends on your data types in Kafka. One example with JSON messages in Kafka could be:

```
import scala.collection.mutable.HashMap

val offsetFinder = new OffsetFinder[String]
val offsets = offsetFinder.getOffsets(
  kafkaSourceTopic,
  kafkaProps,
  message => {
   parseJson(message).getTimestamp().toLong()
  },
  1501601790720L
  )

val kafkaOffsets = new HashMap[KafkaTopicPartition, Long] 
for (o <- offsets) {
  kafkaOffsets.put(new KafkaTopicPartition(kafkaSourceTopic, o._1.partition()), o._2)
}    
val consumer = new FlinkKafkaConsumer010[Tuple](kafkaSourceTopic, ...)
consumer.setStartFromSpecificOffsets(kafkaOffsets)
```

**Comment by feloxx** [comment]
oh...
I seem to understand

I only have a small amount of data.
> Kafka's file partition 0 
> -rw-r--r-- 1 root root 10485760 Feb 24 16:02 00000000000003926192.index
-rw-r--r-- 1 root root 83329269 Feb 24 16:02 00000000000003926192.log
-rw-r--r-- 1 root root 10485756 Feb 24 16:02 00000000000003926192.timeindex

So,'extract' and 'seekTime' whatever it is.
0 partition will only return '3926192'


If I want to get a more precise offset,Is there any way?

**Comment by franklauterwald** [comment]
Hello,

I´m not sure if I understand what you are trying to do. So I will give you an example:
Every record in Kafka has an offset:
```
Offset  Record
    1  [Some Data]
    2  [Some Data]
    3  [Some Data]
    4  [Some Data]
```
Kafka expires (throws away) old data, but keeps increasing the offsets. After some time, your topic could look like this:

```
Offset    Record
3926190  [Some Data]
3926191  [Some Data]
3926192  [Some Data]
3926193  [Some Data]
```

Now there may be timestamps within your data. In our case the data is in JSON format:

```
Offset    Record
3926190  "{timestamp: 1501601790700L, value: 1}"
3926191  "{timestamp: 1501601790710L, value: 7}"
3926192  "{timestamp: 1501601790720L, value: 3}"
3926193  "{timestamp: 1501601790740L, value: 12}"
```
The timestamps are assumed to be unix timestamps (milliseconds since 1970-01-01).
The seekTime is the timestamp you are looking for.
The extract method can determine a timestamp for a Kafka record. In our example, if you pass
`"{timestamp: 1501601790720L, value: 3}"` to extract, it should return `1501601790720L`.

So what does the KafkaOffsetFinder do? It looks for a specific offset in your data.
Assume you want to read all records that have a timestamp of 1501601790718L or newer.
Then you pass 1501601790718L as seekTime and get 3926192 as a result.

If you tell Kafka to seek to 3926192 and then read data, you will get:
```
Offset    Record
3926192  "{timestamp: 1501601790720L, value: 3}"
3926193  "{timestamp: 1501601790740L, value: 12}"
```
So you get exactly the records that have a timestamp > seekTime.

I hope this helps you a liitle.

Cheers,

Frank
